
export const PrLinesData: any = [
  {
    LINE_NO: 66989,
    ITEM_CODE: 'PR23014617',
    DESCRIPTION: 'Level Switches for O&amp;M',
    CREATION_DATE: '57:56.0',
    ApprovedDate: '29:59.3',
    SiteName: 113,
    PROJECT_NAME: 'NULL',
    DEPARTMENTNAME: '2331 - Electrical &amp; Instrumentation',
    PRTYPE: 'Revenue Supply',
    PRSubType: 'General',
    REQUESTED_BY: 'Surendra Kumar Soni',
    TotalValue: 38370,
    AssignBuyer: 'VIJAY CHAPLOT',
    BUYERSTATUS: 'In Process',
  },
  {
    prid: 66854,
    PR_NUM: 'PR23014484',
    DESCRIPTION: 'Pneumatic Fittings for Bag Filter Modification',
    CREATION_DATE: '09:15.0',
    ApprovedDate: '44:44.6',
    SiteName: 113,
    PROJECT_NAME: 'NULL',
    DEPARTMENTNAME: '2331 - Electrical &amp; Instrumentation',
    PRTYPE: 'Revenue Supply',
    PRSubType: 'Breakdown',
    REQUESTED_BY: 'Surendra Kumar Soni',
    TotalValue: 2800,
    AssignBuyer: 'VIJAY CHAPLOT',
    BUYERSTATUS: 'Pending',
  },
];
